version: "3"
services:
  nginx:
    image: nginx:1.13.12-alpine
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
      - ./www/localme.io/:/usr/share/nginx/html/