version: "3"
services:
  nginx:
    image: nginx:1.13.12-alpine
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
      - ./www/localme.io/:/usr/share/nginx/html/
      - ./etc/letsencrypt/live/localme.io/fullchain.pem:/etc/letsencrypt/live/localme.io/fullchain.pem
      - ./etc/letsencrypt/live/localme.io/privkey.pem:/etc/letsencrypt/live/localme.io/privkey.pem
      - ./etc/letsencrypt/dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
